# Generated by Django 4.2.1 on 2023-05-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_studs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
